
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.SUPABASE_URL || "https://dimdaigehnbfigtydyrx.supabase.co";
const SUPABASE_KEY = process.env.SUPABASE_SECRET_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbWRhaWdlaG5iZmlndHlkeXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MzUwODAsImV4cCI6MjA1NzAxMTA4MH0.eWC-d8zw7VjrY-oCa5Da-dyOiCF2XIfKXDvaHKn_GXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY);
